### PR TITLE
Added Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by tiagoFlach**

### CODE REVIEW

**Comment by SoongNoonien** [comment]
Hi!
Thank you very much for the translation! I'd like to add your name and possibly email address to the AUTHORS file and to the about dialog. What should I put there? Or do you want to do it yourself?

**Comment by tiagoFlach** [comment]
I added it now.

**Comment by SoongNoonien** [comment]
You only added it to the AUTHORS file. So you don't want to appear in the about dialog or did you just not find the respective file?

**Comment by tiagoFlach** [comment]
Sorry my friend, now the pull request is complete.

**Comment by SoongNoonien** [comment]
Thanks, but it seems like you changed the formatting of the Readme for no apparent reason. Maybe your editor has some auto formatting settings enabled? I'll fix that and then merge it.

**Comment by SoongNoonien** [comment]
Ok, I've reverted the formatting changes and put everything in one commit.

**Pull request merged**
