### PR TITLE
Update fallback cover image

### PR DESCRIPTION
**Pull request by vixalien**
This icon is more supported, and looks better than the old CD imo.

### CODE REVIEW

**Comment by vixalien** [comment]
image

**Comment by SoongNoonien** [comment]
What do you mean with more supported?

**Comment by vixalien** [comment]
I mean that it's supported by more icon themes.

**Comment by SoongNoonien** [comment]
I don't like the `audio-x-generic` because it is squashed to one side with the default adwaita icons. I could imaging drawing a custom one. Ideally this would be a generic album cover but I'm not sure what makes a generic album cover.

**Comment by vixalien** [comment]
What do you mean squashed to one side?

I believe the icon is also similar to what Amberol, Valent and more uses.

**Comment by SoongNoonien** [comment]
> What do you mean squashed to one side?

The left leg of the note touches the left side of the canvas while right leg doesn't. This is because the designer of the icon tried to make it visually balanced. Which works as intended when the icon is used as intended. But here the icon is used in a confined space with hard borders and this looks off in my opinion.

**Comment by SoongNoonien** [comment]
Here is how it is used in Amberol. Note that the note is not full size.
Bildschirmfoto vom 2024-10-30 19-50-08

**Comment by SoongNoonien** [comment]
I'm using now a simple gray gradient as a fallback cover.

**Pull request closed without merging**
