### PR TITLE
Add rounded corners to cover art

### PR DESCRIPTION
**Pull request by vixalien**

### CODE REVIEW

**Comment by vixalien** [comment]
> With covers which aren't square this isn't working correctly.

Can you show me, I don't have covers that aren't square.

> Here are two screenshots of the same cover, one screenshot is from the album list using Gtk.Picture and the other is from the album page using Gtk.Image

You're right. I don't know why but it seems like `Gtk.Picture` doesn't work that well with rounded corners. I will investigate.

**Comment by vixalien** [comment]
I have fixed the `Gtk.Picture` looking weird when rounded. Can I see how it looks like for non-square covers?

**Comment by vixalien** [comment]
The picture probably needs `valign=CENTER` too. It would be nice if you can check if that fixes it as I don't have a non-square cover.

**Comment by SoongNoonien** [comment]
I thought so too, but this makes the square covers look broken again.
Bildschirmfoto vom 2024-10-30 19-02-12

**Comment by SoongNoonien** [comment]
Also vertical covers which worked before with just `halign=Gtk.Align.CENTER` are broken again now too.
Bildschirmfoto vom 2024-10-30 19-03-24

**Comment by SoongNoonien** [comment]
Apparently I'm not allowed to push to your branch?

**Comment by SoongNoonien** [comment]
This is all I can do right now. Everything is working except for tall covers in the list.

**Comment by SoongNoonien** [comment]
Ok, I found the problem and everything should be fixed now.

**Pull request merged**
