### PR TITLE
Add Persian l10n.

### PR DESCRIPTION
**Pull request by danialbehzadi**

### CODE REVIEW

**Comment by SoongNoonien** [comment]
Thank you very much! But why did you change the order of the languages in the same commit?

**Comment by danialbehzadi** [comment]
> But why did you change the order of the languages in the same commit?

To make it in alphabetic order

**Comment by SoongNoonien** [comment]
Yeah, I see that. But I was wondering why you did everything in one commit. Now it is not so easy to see what changed in `LINGUAS`. Let's revert the reordering and after it's merged I'll rework the readme and make the `LINGUAS` alphabetical.

**Comment by danialbehzadi** [comment]
I reverted the order.

**Comment by SoongNoonien** [comment]
Ok, thanks again!

**Pull request merged**
