### PR TITLE
Add Hindi translation

### PR DESCRIPTION
**Pull request by Scrambled777**
Initial Hindi `hi` language translation.

### CODE REVIEW

**Comment by SoongNoonien** [comment]
Hi!
Thanks for the translation. Would you like to be added to the authors list?

**Comment by Scrambled777** [comment]
> Hi! Thanks for the translation. Would you like to be added to the authors list?

I am really not sure, as this is the first time I had been asked that question.

I just translated so I don't think I deserve to be there.

**Comment by Scrambled777** [comment]
> In the `AUTHORS` file in the root of the repo and the about dialog (`data/AboutDialog.ui`) there are separate sections just for translators.

In that case, kindly also include me.

Really appreciate your responses. Cheers.

**Comment by SoongNoonien** [comment]
Ok, with your GitHub user account name or your clear name? And with an e-mail address for questions/suggestions about the Hindi translation? If you don't want to post them here you can send me an e-mail or put them in yourself.

**Comment by Scrambled777** [comment]
> Ok, with your GitHub user account name or your clear name? And with an e-mail address for questions/suggestions about the Hindi translation? If you don't want to post them here you can send me an e-mail or put them in yourself.

Scrambled777 <weblate.scrambled777@simplelogin.com>

Above name and email.

**Comment by SoongNoonien** [comment]
Ok, nice! I will merge this and add your name when I get home today.

**Comment by Scrambled777** [comment]
> Ok, nice! I will merge this and add your name when I get home today.

Thank you very much. Have a nice day mate. Cheers.

**Comment by Scrambled777** [comment]
@SoongNoonien Thanks for accepting my translation. Cheers mate.

**Pull request merged**
