### PR TITLE
Russian Localization

### PR DESCRIPTION
**Pull request by greenvorbisfan**
Hello. I translated the interface into Russian (it seems I haven’t forgotten anything)

### CODE REVIEW

**Comment by SoongNoonien** [comment]
Hi! Thank you very much. I've taken the liberty to rework the git history, there where some unrelated changes in the `.gitignore` file and you accidentally added a `.mo` file. You can disable the automatic creation of these `.mo` files in Poedit.

I don't speak any Russian but I wonder if the translation of "{channels} channels" as "{channels} канала(ов)" is intended. Shouldn't it be something like "{channels} каналы" without the parenthesis?

I'd like to add your name and possibly e-mail address to the `AUTHORS` file and the info dialog in the application. Is that ok with you?

**Comment by SoongNoonien** [comment]
> it seems I haven’t forgotten anything

Just a view minor things like the `LINGUAS` file and the readme but I can fix them if you like.

**Comment by greenvorbisfan** [comment]
> Shouldn't it be something like "{channels} каналы" without the parenthesis?

There are several plural forms here. I speak English very poorly, but I'll try to explain:
1 channel = 1 канал
2 (3, 4, 22, 23, 24) channels = 2 (3, 4, 22, 23, 24) канал**а**
5 (6, 7 etc) channels = 5 (etc) канал**ов**
Such a difficult Russian language 😊

> I'd like to add your name and possibly e-mail address to the AUTHORS file and the info dialog in the application. Is that ok with you?

Yes, that will be good. Thanks.

**Comment by SoongNoonien** [comment]
>  Such a difficult Russian language 😊

Very interesting! I thought that these plural forms should be possible to translate with [gettext](https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html).

>>    I'd like to add your name and possibly e-mail address to the AUTHORS file and the info dialog in the application. Is that ok with you?

>Yes, that will be good. Thanks.

Ok, which e-mail address should I use?

**Comment by greenvorbisfan** [comment]
> I thought that these plural forms should be possible to translate with [gettext](https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html).

Unfortunately, I don't know how to do this.

> Ok, which e-mail address should I use?

alexander.froloff@mxc.ru (it seems like I entered it in the `.po` file)

**Comment by SoongNoonien** [comment]
> Unfortunately, I don't know how to do this.

I think I've fixed it. Please take a look at the `.po` again. The plural forms of "канал" are now implemented as you explained above. Unfortunately I don't know the respective plural forms of "день" and "трек".

> [alexander.froloff@mxc.ru](mailto:alexander.froloff@mxc.ru) (it seems like I entered it in the .po file)

Sorry, I missed that.

**Comment by greenvorbisfan** [comment]
> "день" and "трек"

1 (21, 31 etc) **день** / **трек**
2 (3, 4, 22, 23, 24 etc) **дня** / **трека**
5-20 (25-30 etc) **дней** / **треков**

**Comment by SoongNoonien** [comment]
Ok, very nice! Thanks, again.

**Pull request merged**
